name: Protect Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from dev branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "dev" ]]; then
            echo "Error: Pull request to 'main' are only allowed from 'dev' branch."
            ecit 1
          fi
